name: Ruby

on:
  - pull_request

env:
  RAILS_ENV: test

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Rubocop Linter
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: gemfile
        rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile rubocop-rspec:gemfile rubocop-i18n:gemfile rubocop-rake:gemfile
        github_token: ${{ secrets.github_token }}
        fail_on_error: true
        filter_mode: diff_context

  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Install required apt packages
      run: |
        sudo apt-get -y install libpq-dev
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Build and test with Rake
      run: |
        bundle exec rails assets:precompile
        bundle exec rails db:setup
        bundle exec rails spec
